const express = require('express');
const { getReports, generateReport, downloadReport, deleteReport } = require('../controllers/reportController');
const { protect } = require('../middleware/auth');
const router = express.Router();
router.use(protect);
router.get('/', getReports);
router.post('/generate', generateReport);
router.get('/:id/download', downloadReport);
router.delete('/:id', deleteReport);
module.exports = router;
